name: Deploy PHP App to Ubuntu Server

on:
  push:
    branches:
      - main  # Deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to Ubuntu server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /var/www/html/myapp
          git pull origin main
          # Optional: Clear cache, restart services, etc.
        EOF
