name: Deploy PHP App to Ubuntu Server

on:
  push:
    branches:
      - main  # Deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy via SSH with fallback
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          if [ ! -d "/var/www/html/.git" ]; then
            echo "Cloning repo as it doesn't exist"
            rm -rf /var/www/html/
            git clone git@github.com:Govindgiri3438/sample-php-application.git /var/www/html/
          else
            echo "Repo exists, pulling latest changes"
            cd /var/www/html/
            git pull origin main
          fi
        EOF
